import type { LucideIcon } from "lucide-react";
import {
  BarChart,
  Bell,
  BookOpen,
  BookOpenText,
  Bot,
  Braces,
  Brain,
  Bug,
  Calendar,
  ChartLine,
  ChartNoAxesColumn,
  ChartPie,
  ClipboardCheck,
  Cloud,
  Code,
  Compass,
  Database,
  FileSpreadsheet,
  FileText,
  Filter,
  FlaskConical,
  GitBranch,
  GitPullRequest,
  Globe,
  Key,
  Landmark,
  Languages,
  Lightbulb,
  ListChecks,
  Lock,
  Mail,
  Megaphone,
  MessageCircleQuestion,
  Microscope,
  Newspaper,
  Package,
  Palette,
  PenLine,
  Presentation,
  Receipt,
  Repeat,
  Rocket,
  Search,
  Server,
  ShieldCheck,
  Sparkles,
  Table,
  Terminal,
  TestTube,
  Timer,
  Workflow,
  Wrench,
  Siren,
  Telescope,
  Users,
} from "lucide-react";
import { parseAvatarEmoji } from "./avatar-emoji";

export const AVATAR_ICON_COMPONENTS = {
  "bar-chart": BarChart,
  bell: Bell,
  "book-open": BookOpen,
  "book-open-text": BookOpenText,
  bot: Bot,
  braces: Braces,
  brain: Brain,
  bug: Bug,
  calendar: Calendar,
  "chart-line": ChartLine,
  "chart-no-axes-column": ChartNoAxesColumn,
  "chart-pie": ChartPie,
  "clipboard-check": ClipboardCheck,
  cloud: Cloud,
  code: Code,
  compass: Compass,
  database: Database,
  "file-spreadsheet": FileSpreadsheet,
  "file-text": FileText,
  filter: Filter,
  "flask-conical": FlaskConical,
  "git-branch": GitBranch,
  "git-pull-request": GitPullRequest,
  globe: Globe,
  key: Key,
  landmark: Landmark,
  languages: Languages,
  lightbulb: Lightbulb,
  "list-checks": ListChecks,
  lock: Lock,
  mail: Mail,
  megaphone: Megaphone,
  "message-circle-question": MessageCircleQuestion,
  microscope: Microscope,
  newspaper: Newspaper,
  package: Package,
  palette: Palette,
  "pen-line": PenLine,
  presentation: Presentation,
  receipt: Receipt,
  repeat: Repeat,
  rocket: Rocket,
  search: Search,
  server: Server,
  "shield-check": ShieldCheck,
  sparkles: Sparkles,
  table: Table,
  terminal: Terminal,
  "test-tube": TestTube,
  timer: Timer,
  workflow: Workflow,
  wrench: Wrench,
  siren: Siren,
  telescope: Telescope,
  users: Users,
} satisfies Record<string, LucideIcon>;

export type AvatarIconName = keyof typeof AVATAR_ICON_COMPONENTS;

const AVATAR_ICON_PREFIX = "icon:";

export function parseAvatarIcon(value?: string | null): AvatarIconName | null {
  if (!value?.startsWith(AVATAR_ICON_PREFIX)) return null;
  const name = value.slice(AVATAR_ICON_PREFIX.length).trim();
  return Object.hasOwn(AVATAR_ICON_COMPONENTS, name) ? name as AvatarIconName : null;
}

export function formatAvatarIcon(name: AvatarIconName): string {
  return AVATAR_ICON_PREFIX + name;
}

// Existing saved emoji avatars remain readable without rewriting user data.
const LEGACY_EMOJI_ICONS: Record<string, AvatarIconName> = {
  "🚀": "rocket", "🐞": "bug", "🚧": "shield-check", "🔭": "telescope",
  "📚": "book-open", "🧹": "wrench", "📦": "package", "🚨": "siren",
  "🔍": "search", "🔎": "search", "📐": "landmark", "🛠": "code",
  "🧪": "test-tube", "🩺": "microscope", "🔬": "microscope",
  "🛡": "shield-check", "🚦": "clipboard-check", "📝": "pen-line",
  "📊": "bar-chart", "📡": "server", "🤖": "bot", "🖥": "globe",
  "🗃": "database", "🧭": "compass", "🚑": "bug", "🔀": "git-pull-request",
  "🐛": "bug", "📄": "file-text",
  "🐙": "workflow", "🦊": "compass", "🦉": "search", "🐝": "workflow",
  "🐼": "bot", "🐸": "bot", "🐯": "shield-check", "🦁": "shield-check",
  "🐨": "bot", "🐵": "bot", "🐧": "terminal", "🐳": "cloud",
  "🦋": "palette", "🌞": "lightbulb", "🌙": "sparkles", "⭐": "sparkles",
  "🔥": "siren", "⚡": "rocket", "🍀": "sparkles", "🌈": "palette",
  "👾": "bot", "🧠": "brain",
};

export function resolveAvatarIcon(value?: string | null): AvatarIconName | null {
  const icon = parseAvatarIcon(value);
  if (icon) return icon;
  const emoji = parseAvatarEmoji(value);
  if (!emoji) return null;
  const normalized = emoji.replace(/\uFE0F/g, "");
  return Object.hasOwn(LEGACY_EMOJI_ICONS, normalized) ? LEGACY_EMOJI_ICONS[normalized]! : "bot";
}

const TONES = {
  research: { text: "text-skill-research", bg: "bg-skill-research/12" },
  design: { text: "text-skill-design", bg: "bg-skill-design/12" },
  engineering: { text: "text-skill-engineering", bg: "bg-skill-engineering/12" },
  quality: { text: "text-skill-quality", bg: "bg-skill-quality/12" },
  operations: { text: "text-skill-operations", bg: "bg-skill-operations/12" },
  writing: { text: "text-skill-writing", bg: "bg-skill-writing/12" },
  data: { text: "text-skill-data", bg: "bg-skill-data/12" },
  other: { text: "text-skill-other", bg: "bg-skill-other/12" },
};

export const AVATAR_ICON_TONE: Record<AvatarIconName, { text: string; bg: string }> = {
  "brain": TONES.research,
  "compass": TONES.research,
  "lightbulb": TONES.research,
  "list-checks": TONES.research,
  "message-circle-question": TONES.research,
  "search": TONES.research,
  "telescope": TONES.research,
  "landmark": TONES.design,
  "palette": TONES.design,
  "braces": TONES.engineering,
  "code": TONES.engineering,
  "git-branch": TONES.engineering,
  "git-pull-request": TONES.engineering,
  "rocket": TONES.engineering,
  "terminal": TONES.engineering,
  "workflow": TONES.engineering,
  "users": TONES.engineering,
  "bot": TONES.quality,
  "bug": TONES.quality,
  "clipboard-check": TONES.quality,
  "flask-conical": TONES.quality,
  "globe": TONES.quality,
  "microscope": TONES.quality,
  "repeat": TONES.quality,
  "shield-check": TONES.quality,
  "test-tube": TONES.quality,
  "bell": TONES.operations,
  "calendar": TONES.operations,
  "cloud": TONES.operations,
  "key": TONES.operations,
  "lock": TONES.operations,
  "package": TONES.operations,
  "server": TONES.operations,
  "siren": TONES.operations,
  "timer": TONES.operations,
  "wrench": TONES.operations,
  "book-open": TONES.writing,
  "book-open-text": TONES.writing,
  "file-text": TONES.writing,
  "languages": TONES.writing,
  "mail": TONES.writing,
  "megaphone": TONES.writing,
  "newspaper": TONES.writing,
  "pen-line": TONES.writing,
  "presentation": TONES.writing,
  "bar-chart": TONES.data,
  "chart-line": TONES.data,
  "chart-no-axes-column": TONES.data,
  "chart-pie": TONES.data,
  "database": TONES.data,
  "file-spreadsheet": TONES.data,
  "filter": TONES.data,
  "receipt": TONES.data,
  "table": TONES.data,
  "sparkles": TONES.other,
};
