import fs from "node:fs";
import path from "node:path";
const source = ".omx/projects-p1-performance";
const target = ".trellis/tasks/10-05-projects-p1-verification/performance/results";
fs.mkdirSync(target,{recursive:true});
const read = (name) => fs.existsSync(path.join(source,name)) ? JSON.parse(fs.readFileSync(path.join(source,name),"utf8")) : null;
const round = (n) => n === null || n === undefined ? "—" : Number(n).toFixed(1);
const baseline = read("baseline-static-static-summary.json");
const current = read("current-full-static-summary.json");
const reachability = (rate) => {
  const file=path.join(source,`current-full-active-${rate}-samples.jsonl`);
  if(!fs.existsSync(file))return null;
  const rows=fs.readFileSync(file,"utf8").trim().split("\n").filter(Boolean).map(JSON.parse);
  const waits=[];let pending=null;
  for(const row of rows){if(row.second_page_attempt){if(pending===null)pending=row.since_start_ms-row.ms;if(row.second_page_success){waits.push(row.since_start_ms-pending);pending=null;}}else pending=null;}
  waits.sort((a,b)=>a-b);
  return {completed_episodes:waits.length,p50_ms:waits.length?waits[Math.ceil(waits.length*.5)-1]:null,p95_ms:waits.length?waits[Math.ceil(waits.length*.95)-1]:null,max_ms:waits.length?waits.at(-1):null,right_censored_wait_ms:pending===null?null:rows.at(-1).since_start_ms-pending};
};
const active = [0,1,10].map(rate=>{const summary=read(`current-full-active-${rate}-summary.json`);return summary?{...summary,reachability:reachability(rate)}:null;});
const complete = !!read("current-full-complete.json");
const resources = (name) => {
  if(!fs.existsSync(path.join(source,name)))return null;
  const samples=fs.readFileSync(path.join(source,name),"utf8").trim().split("\n").filter(Boolean).map(JSON.parse).filter(row=>row.rss_kib);
  return {samples:samples.length,max_cpu_percent:Math.max(...samples.map(row=>row.cpu_percent)),max_rss_mib:Math.max(...samples.map(row=>row.rss_kib))/1024,first:samples[0]?.at,last:samples.at(-1)?.at};
};
const summary = {generated_at:new Date().toISOString(),complete,budget:JSON.parse(fs.readFileSync(".trellis/tasks/10-05-projects-p1-verification/performance/budget.json")),baseline,current,active,resources:{baseline:resources("baseline-resource-resource-samples.jsonl"),current:resources("current-resource-samples.jsonl")},provenance:read("current-provenance.json"),build_ledger:read("current-build-ledger.json"),full_scope_audit:read("current-full-scope-audit.json")};
const measurements = fs.readdirSync(source).filter(name => /-(samples\.json|samples\.jsonl|summary\.json|metadata\.json|query-observation\.json|exact-query-plans\.json|cold-process-samples\.json|fixture-audit\.json|full-scope-audit\.json|provenance\.json|build-ledger\.json)$/.test(name));
for(const name of measurements)fs.copyFileSync(path.join(source,name),path.join(target,name));
fs.writeFileSync(path.join(target,"summary.json"),JSON.stringify(summary,null,2));
const lines=["# P1 API 与活跃分页性能验收", "", `状态：${complete?"完整采样已结束；性能未通过：静态延迟通过，但1/s与10/s活跃分页未达到可用性门槛":"持续采样中，不能据此宣称完整性能验收通过"}。生成时间 ${summary.generated_at}。`, "", "## 预算与环境", "", "测量前固定 HTTP P95≤2,000ms、错误0、同版本计数/页一致100%；双客户端收敛≤5,000ms由 browser lane 独立执行。空闲第二页成功率至少95%；持续变更低于50%明确标为不可用，需复审 ADR。未按结果移动阈值。", "", "- 主机 Apple M4，10 CPU、16 GiB，macOS 25.2 arm64；Go 1.27.0；容器 PostgreSQL 17.11 aarch64，pg_stat_statements未启用。", "- 实现前基线是 `git archive 0af59c5d5 server` 后独立编译、独立数据库与19072端口，绝非新接口冒充旧基线。", "- 新接口是19071运行中的 `bb1c20dcb` 二进制原样复制到独占19073，源运行记录source_id为 `5dd65e9bbe9887d792e93ef488cde8c4299657594b6b6177cbce22650152f197`；二进制SHA256与各次 `/health` PID/commit/started_at均保存在结果中。", "- 两库各500项目：目标项目10,000正式任务，另100 pending+100 rejected+100 duplicate；其余499项目各10正式任务，总计15,290任务。真实HTTP登录/建工作空间；批量fixture用已有TestApiClient与参数化SQL。没有执行任务。", "- 同一认证成员发压测；并发1/10分别200请求，每接口20次预热。冷样本指5次新API进程的首个业务请求；数据库和OS缓存仍热，不称整机冷启动。", "- 静态窗口有其他团队构建/测试共享本机资源；活跃0/s窗口还包含独立查询计数与全量页核对的短时读负载。全部请求原始耗时保留，未剔除离群点。", "", "## 静态 HTTP 延迟", "", "单位ms。旧 API只有项目详情及列表，新增overview/risk没有伪造旧值。", "", "| 接口 | 并发 | 旧P50 | 旧P95 | 新P50 | 新P95 | 新错误 | ≤2s |", "| --- | ---: | ---: | ---: | ---: | ---: | ---: | --- |"];
for(const [key,row] of Object.entries(current??{})){const old=baseline?.[key];lines.push(`| ${key.replace(/_c\d+$/,'')} | ${row.concurrency} | ${round(old?.p50_ms)} | ${round(old?.p95_ms)} | ${round(row.p50_ms)} | ${round(row.p95_ms)} | ${row.errors} | ${row.budget_pass?"通过":"失败"} |`);}
lines.push("", "新旧项目API的绝对延迟通过2秒门槛，但并发10的旧详情P95约12.2→46.3ms、500项目列表约29.4→121.9ms，属于明显相对回归。新增分项及RR授权事务增大SQL数量，不能只报告新增接口很快。", "", "## 实际 SQL 与资源", "", "通过仅对独占查询实例的连接设置 `log_min_duration_statement=0`，按私库backend PID和请求时间窗口读取PostgreSQL日志中的execute/statement，排除Parse/Bind计时项。该日志开关未用于正式延迟窗口，也没有修改共享PostgreSQL全局配置。每endpoint额外发5次真实HTTP请求，保留SQL名称直方图和docker命令。", "", "- 旧详情／列表：各5条SQL/request。", "- 新详情／列表：各13条statement/request（包括BEGIN、SET TRANSACTION、COMMIT）。", "- 新overview：20条statement/request；四风险页：22条。blocked观测窗口额外出现1次ping和4次后台webhook claim，原始总数115/5=23，明确扣除这5条后台语句后为22，未将后台负载伪装为请求查询。", "- 所有页的查询数随本次接口形状固定，不随项目数产生N+1。EXPLAIN ANALYZE/BUFFERS/JSON包含正式输入、旧单项目／500项目统计、新500项目分类统计和50项页面读取，保存完整plan。", "", `CPU/RSS样本：旧峰值 ${round(summary.resources.baseline?.max_cpu_percent)}% / ${round(summary.resources.baseline?.max_rss_mib)} MiB；新峰值 ${round(summary.resources.current?.max_cpu_percent)}% / ${round(summary.resources.current?.max_rss_mib)} MiB。CPU按ps进程口径可大于100%；新采样覆盖后半静态窗口及活跃窗口，旧在独立资源重复运行中采样。`, "", "## 同版本完整集合核对", "", "独立SQL与真实API逐页遍历核对，非仅检查第一页或两个同源计数字段：blocked 1,000项/10页、overdue 3,333项/34页、unassigned 2,000项/20页、in_review 1,000项/10页，按100页大小；全部ID、排序、总数和snapshot_version一致，agreement=100%。执行在0/s稳定窗口，保存实际所有ID。", "", "## 活跃分页（每种负载至少10分钟）", "", "每秒翻一页；后台每秒0/1/10次真实DB变化，轮换截止日期、指派和准入状态，限定自己的工作空间/任务。每阶段恢复相同初始fixture。", "", "| 变更/s | 时长s | 页请求 | P95ms | 错误 | 刷新比例 | 第二页成功/尝试 | 成功率 | 最长连续重置 |", "| ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |");
for(let i=0;i<3;i++){const row=active[i];lines.push(row?`| ${[0,1,10][i]} | ${round(row.elapsed_seconds)} | ${row.samples} | ${round(row.p95_ms)} | ${row.errors} | ${round(row.refresh_ratio*100)}% | ${row.second_page_successes}/${row.second_page_attempts} | ${round(row.second_page_success_ratio*100)}% | ${row.max_consecutive_resets} |`:`| ${[0,1,10][i]} | 待完成 | — | — | — | — | — | — | — |`);}
lines.push("", "到第二页等待时长从首次下一页请求开始，包含重置后的定时重试；与单个成功HTTP耗时分开。未在观察窗内到达的事件为右删失，不伪造P95：", "", "| 变更/s | 到达事件 | 等待P50ms | 等待P95ms | 最长等待ms | 结束时仍未到达的已观察等待ms |", "| ---: | ---: | ---: | ---: | ---: | ---: |");
for(let i=0;i<3;i++){const reach=active[i]?.reachability;if(reach)lines.push(`| ${[0,1,10][i]} | ${reach.completed_episodes} | ${round(reach.p50_ms)} | ${round(reach.p95_ms)} | ${round(reach.max_ms)} | ${round(reach.right_censored_wait_ms)} |`);}
lines.push("", "完整采样证明持续变更会反复回到第一页：全输入digest改变就重置，后续页面难以到达。HTTP成功和计数正确不等于分页可用；两档活跃负载均低于预算，必须将其作为未完成风险交由父任务复审ADR-01，不能以Playwright脚本执行成功替代产品通过。", "", "## 可复现命令与证据", "", "```sh", "# repository root; the env file contains only this lane's isolated database/port", "set -a", "source .omx/projects-p1-performance/baseline.env", "set +a", "PERF_LABEL=baseline PERF_MODE=static pnpm exec playwright test --config=.trellis/tasks/10-05-projects-p1-verification/performance/playwright.config.ts", "set -a", "source .omx/projects-p1-performance/current.env", "set +a", "PERF_LABEL=current PERF_MODE=full pnpm exec playwright test --config=.trellis/tasks/10-05-projects-p1-verification/performance/playwright.config.ts", "# Dedicated SQL-logging observer (same private database, a separate owned API port)", "PORT=19074 NEXT_PUBLIC_API_URL=http://localhost:19074 PERF_LABEL=current PERF_MODE=queries pnpm exec playwright test --config=.trellis/tasks/10-05-projects-p1-verification/performance/playwright.config.ts", "node .trellis/tasks/10-05-projects-p1-verification/performance/full-scope-audit.mjs", "node .trellis/tasks/10-05-projects-p1-verification/performance/report.mjs", "```", "", "可复用脚本与预算位于 `performance/`，原始请求/活跃页/CPU样本、冷启动PID、SQL直方图、EXPLAIN和汇总位于 [performance/results/summary.json](performance/results/summary.json)。认证token只保留在ignored的私有session文件，不复制到报告。大型源码archive和测试二进制留在ignored的 `.omx/projects-p1-performance/`；并未改动原main或19071服务。", "", "跨端30次收敛、Web最终版本和新的健康实现如果发生变化，须由父任务追加关联证据；本报告当前只绑定已记录的二进制与源码。");
fs.writeFileSync(".trellis/tasks/10-05-projects-p1-verification/performance-report.md",lines.join("\n")+"\n");
console.log(JSON.stringify({complete,files_copied:measurements.length,active_complete:active.filter(Boolean).length}));
