// @vitest-environment node
import { createHash } from "node:crypto";
import { spawnSync } from "node:child_process";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { setTimeout } from "node:timers/promises";
import { afterEach, describe, expect, it } from "vitest";
import { collectArtifacts, publishArtifacts } from "./update-artifacts.mjs";

const roots = [];
const cli = join(dirname(fileURLToPath(import.meta.url)), "update-artifacts.mjs");

function fixture() {
  const root = mkdtempSync(join(tmpdir(), "multica-updates-"));
  roots.push(root);
  const source = join(root, "source");
  mkdirSync(source);
  return { root, source, destination: join(root, "storage") };
}

function release(source, { version = "1.2.3", channel = "latest.yml", platform = "windows-x64", extension = "exe", bytes = "installer bytes", nested = "" } = {}) {
  const directory = join(source, nested);
  mkdirSync(directory, { recursive: true });
  const name = `multica-desktop-${version}-${platform}.${extension}`;
  const hash = createHash("sha512").update(bytes).digest("base64");
  const metadata = `version: ${version}\nfiles:\n  - url: ${name}\n    sha512: ${hash}\n    size: ${Buffer.byteLength(bytes)}\npath: ${name}\nsha512: ${hash}\nreleaseDate: '2026-09-24T00:00:00.000Z'\n`;
  writeFileSync(join(directory, name), bytes);
  writeFileSync(join(directory, `${name}.blockmap`), "blockmap bytes");
  writeFileSync(join(directory, channel), metadata);
  return { name, metadata, channel, directory };
}

afterEach(() => { while (roots.length) rmSync(roots.pop(), { recursive: true, force: true }); });

describe("desktop update artifact collection", () => {
  it("flattens platform outputs, preserves generated bytes, and omits unpacked/debug files", async () => {
    const f = fixture();
    const win = release(f.source, { nested: "win-ia32", platform: "windows-ia32", channel: "latest-ia32.yml" });
    const mac = release(f.source, { nested: "mac-arm64", platform: "mac-arm64", extension: "zip", channel: "latest-mac.yml" });
    const dmg = mac.name.replace(/zip$/, "dmg");
    writeFileSync(join(mac.directory, dmg), "first-install dmg");
    writeFileSync(join(f.source, "builder-debug.yml"), "debug");
    release(f.source, { nested: "win-ia32/win-ia32-unpacked", version: "9.9.9" });
    await collectArtifacts(f);
    expect(readdirSync(f.destination).sort()).toEqual([win.name, `${win.name}.blockmap`, win.channel, mac.name, `${mac.name}.blockmap`, mac.channel, dmg].sort());
    expect(readFileSync(join(f.destination, win.channel), "utf8")).toBe(win.metadata);
    expect(readFileSync(join(win.directory, win.channel), "utf8")).toBe(win.metadata);
  });

  it("accepts identical duplicate outputs but refuses conflicting files before copying", async () => {
    const f = fixture();
    const a = release(f.source);
    release(f.source, { nested: "win-x64" });
    await collectArtifacts(f);
    writeFileSync(join(f.source, "win-x64", a.name), "conflicting bytes");
    await expect(collectArtifacts({ ...f, destination: join(f.root, "other") })).rejects.toThrow(/conflicting duplicate/i);
    expect(existsSync(join(f.root, "other", a.channel))).toBe(false);
  });

  it.each(["https://evil.example/file.exe", "//evil.example/file.exe", "../file.exe", "..\\file.exe", "file.exe?token=1", "%2e%2e%2ffile.exe", "/tmp/file.exe"])("rejects unsafe metadata reference %s", async (reference) => {
    const f = fixture();
    const a = release(f.source);
    writeFileSync(join(f.source, a.channel), a.metadata.replaceAll(a.name, JSON.stringify(reference)));
    await expect(collectArtifacts(f)).rejects.toThrow(/unsafe|filename/i);
    expect(existsSync(join(f.destination, a.channel))).toBe(false);
  });

  it.each(["missing", "size", "sha512", "legacy checksum", "malformed YAML", "no files"])("rejects %s before exposing metadata", async (kind) => {
    const f = fixture();
    const a = release(f.source);
    if (kind === "missing") rmSync(join(f.source, a.name));
    if (kind === "size") writeFileSync(join(f.source, a.channel), a.metadata.replace("size: 15", "size: 999"));
    if (kind === "sha512") writeFileSync(join(f.source, a.name), "changed content");
    if (kind === "legacy checksum") writeFileSync(join(f.source, a.channel), a.metadata.replace(/\nsha512: .+/, `\nsha512: ${createHash("sha512").update("wrong").digest("base64")}`));
    if (kind === "malformed YAML") writeFileSync(join(f.source, a.channel), "version: [");
    if (kind === "no files") writeFileSync(join(f.source, a.channel), "version: 1.2.3\nfiles: []\n");
    await expect(collectArtifacts(f)).rejects.toThrow();
    expect(existsSync(join(f.destination, a.channel))).toBe(false);
  });

  it("rejects prereleases by default and explicitly allows smoke-test builds", async () => {
    const f = fixture();
    const a = release(f.source, { version: "1.2.3-dirty" });
    await expect(collectArtifacts(f)).rejects.toThrow(/prerelease|stable/i);
    await collectArtifacts({ ...f, allowPrerelease: true });
    expect(readFileSync(join(f.destination, a.channel), "utf8")).toBe(a.metadata);
  });

  it("rejects symlink artifacts and destination/source overlap", async () => {
    const f = fixture();
    const a = release(f.source);
    rmSync(join(f.source, a.name));
    writeFileSync(join(f.root, "outside.exe"), "installer bytes");
    symlinkSync(join(f.root, "outside.exe"), join(f.source, a.name));
    await expect(collectArtifacts(f)).rejects.toThrow(/symlink|regular file/i);
    await expect(collectArtifacts({ ...f, destination: join(f.source, "output") })).rejects.toThrow(/overlap/i);
  });
});

describe("desktop update publication", () => {
  it("publishes immutable artifacts and metadata, retains old files and privately snapshots old metadata", async () => {
    const f = fixture();
    const first = release(f.source);
    await publishArtifacts(f);
    const second = release(f.source, { version: "1.2.4", bytes: "new installer" });
    await publishArtifacts(f);
    const publicDirectory = join(f.destination, "public");
    expect(readFileSync(join(publicDirectory, first.name), "utf8")).toBe("installer bytes");
    expect(readFileSync(join(publicDirectory, second.channel), "utf8")).toBe(second.metadata);
    const snapshots = readdirSync(join(f.destination, "backups"));
    expect(snapshots).toHaveLength(1);
    expect(readFileSync(join(f.destination, "backups", snapshots[0], first.channel), "utf8")).toBe(first.metadata);
    expect(readdirSync(publicDirectory).some((name) => name.startsWith("."))).toBe(false);
    expect(readdirSync(join(f.destination, "staging"))).toEqual([]);
    expect(existsSync(join(f.destination, ".publish.lock"))).toBe(false);
  });

  it("leaves active metadata unchanged on bad checksums or immutable filename replacement", async () => {
    const f = fixture();
    const first = release(f.source);
    await publishArtifacts(f);
    const second = release(f.source, { version: "1.2.4" });
    writeFileSync(join(f.source, second.name), "corrupted");
    await expect(publishArtifacts(f)).rejects.toThrow(/size|SHA-512/i);
    expect(readFileSync(join(f.destination, "public", first.channel), "utf8")).toBe(first.metadata);
    release(f.source, { version: "1.2.4" });
    writeFileSync(join(f.source, `${first.name}.blockmap`), "replace historical blockmap");
    await expect(publishArtifacts(f)).rejects.toThrow(/immutable/i);
    expect(readFileSync(join(f.destination, "public", first.channel), "utf8")).toBe(first.metadata);
    expect(existsSync(join(f.destination, "public", second.name))).toBe(false);
  });

  it("exposes complete artifact bytes before switching whole metadata files", async () => {
    const f = fixture();
    const first = release(f.source);
    await publishArtifacts(f);
    const bytes = Buffer.alloc(8 * 1024 * 1024, 98);
    const second = release(f.source, { version: "1.2.4", bytes });
    const publicDirectory = join(f.destination, "public");
    let completed = false;
    const publishing = publishArtifacts(f).finally(() => { completed = true; });
    const inspect = () => {
      const metadata = readFileSync(join(publicDirectory, second.channel), "utf8");
      expect([first.metadata, second.metadata]).toContain(metadata);
      const artifact = join(publicDirectory, second.name);
      if (metadata === second.metadata) expect(existsSync(artifact)).toBe(true);
      if (existsSync(artifact)) expect(readFileSync(artifact).equals(bytes)).toBe(true);
    };
    try {
      while (!completed) {
        inspect();
        await setTimeout(1);
      }
      inspect();
    } finally {
      await publishing;
    }
    expect(readFileSync(join(publicDirectory, second.channel), "utf8")).toBe(second.metadata);
  });

  it("serializes competing publishers and refuses an existing lock without deleting it", async () => {
    const f = fixture();
    const a = release(f.source, { bytes: Buffer.alloc(1024 * 1024, 97) });
    const results = await Promise.allSettled([publishArtifacts(f), publishArtifacts(f)]);
    expect(results.filter((result) => result.status === "fulfilled")).toHaveLength(1);
    const failed = results.find((result) => result.status === "rejected");
    expect(failed.reason.message).toMatch(/lock|publisher/i);
    const lock = join(f.destination, ".publish.lock");
    mkdirSync(lock);
    writeFileSync(join(lock, "owner.json"), "other publisher");
    await expect(publishArtifacts(f)).rejects.toThrow(/lock|publisher/i);
    expect(readFileSync(join(lock, "owner.json"), "utf8")).toBe("other publisher");
    expect(readFileSync(join(f.destination, "public", a.channel), "utf8")).toBe(a.metadata);
  });

  it("rejects a symlink public directory without writing into it", async () => {
    const f = fixture();
    release(f.source);
    mkdirSync(f.destination);
    const elsewhere = join(f.root, "elsewhere");
    mkdirSync(elsewhere);
    symlinkSync(elsewhere, join(f.destination, "public"));
    await expect(publishArtifacts(f)).rejects.toThrow(/symlink|directory/i);
    expect(readdirSync(elsewhere)).toEqual([]);
  });

  it("implements both CLI commands with explicit arguments and failure exit codes", () => {
    const f = fixture();
    const a = release(f.source);
    const run = (...args) => spawnSync(process.execPath, [cli, ...args], { encoding: "utf8" });
    expect(run("collect", "--source", f.source, "--destination", join(f.root, "collected")).status).toBe(0);
    expect(run("publish", "--source", join(f.root, "collected"), "--destination", f.destination).status).toBe(0);
    expect(readFileSync(join(f.destination, "public", a.channel), "utf8")).toBe(a.metadata);
    expect(run("publish", "--source", f.source).status).not.toBe(0);
    expect(run("publish", "--source", f.source, "--destination", f.destination, "--unknown").status).not.toBe(0);
  });
});
