import type { LucideIcon } from "lucide-react";
import {
  BarChart,
  Bell,
  BookOpen,
  BookOpenText,
  Bot,
  Braces,
  Brain,
  Bug,
  Calendar,
  ChartLine,
  ChartNoAxesColumn,
  ChartPie,
  ClipboardCheck,
  Cloud,
  Code,
  Compass,
  Database,
  FileSpreadsheet,
  FileText,
  Filter,
  FlaskConical,
  GitBranch,
  GitPullRequest,
  Globe,
  Key,
  Landmark,
  Languages,
  Lightbulb,
  ListChecks,
  Lock,
  Mail,
  Megaphone,
  MessageCircleQuestion,
  Microscope,
  Newspaper,
  Package,
  Palette,
  PenLine,
  Presentation,
  Receipt,
  Repeat,
  Rocket,
  Search,
  Server,
  ShieldCheck,
  Sparkles,
  Table,
  Terminal,
  TestTube,
  Timer,
  Workflow,
  Wrench,
} from "lucide-react";
import {
  resolveSkillIconName,
  type SkillCategory,
  type SkillIconName,
  type SkillPresentationMeta,
} from "@multica/core/skills";

// Named imports on purpose: the whitelist in @multica/core is the contract,
// and a `Record<SkillIconName, ...>` makes the compiler refuse a whitelist
// entry that has no component here (or a stale component with no entry).
export const SKILL_ICON_COMPONENTS: Record<SkillIconName, LucideIcon> = {
  "bar-chart": BarChart,
  bell: Bell,
  "book-open": BookOpen,
  "book-open-text": BookOpenText,
  bot: Bot,
  braces: Braces,
  brain: Brain,
  bug: Bug,
  calendar: Calendar,
  "chart-line": ChartLine,
  "chart-no-axes-column": ChartNoAxesColumn,
  "chart-pie": ChartPie,
  "clipboard-check": ClipboardCheck,
  cloud: Cloud,
  code: Code,
  compass: Compass,
  database: Database,
  "file-spreadsheet": FileSpreadsheet,
  "file-text": FileText,
  filter: Filter,
  "flask-conical": FlaskConical,
  "git-branch": GitBranch,
  "git-pull-request": GitPullRequest,
  globe: Globe,
  key: Key,
  landmark: Landmark,
  languages: Languages,
  lightbulb: Lightbulb,
  "list-checks": ListChecks,
  lock: Lock,
  mail: Mail,
  megaphone: Megaphone,
  "message-circle-question": MessageCircleQuestion,
  microscope: Microscope,
  newspaper: Newspaper,
  package: Package,
  palette: Palette,
  "pen-line": PenLine,
  presentation: Presentation,
  receipt: Receipt,
  repeat: Repeat,
  rocket: Rocket,
  search: Search,
  server: Server,
  "shield-check": ShieldCheck,
  sparkles: Sparkles,
  table: Table,
  terminal: Terminal,
  "test-tube": TestTube,
  timer: Timer,
  workflow: Workflow,
  wrench: Wrench,
};

/**
 * Category tone classes. Colour always follows the category (never the icon
 * override) so every card in a category shares one hue. Tokens live in
 * `packages/ui/styles/tokens.css` as `--skill-<category>`.
 */
export const SKILL_CATEGORY_TONE: Record<
  SkillCategory,
  { text: string; bg: string; dot: string }
> = {
  research: { text: "text-skill-research", bg: "bg-skill-research/12", dot: "bg-skill-research" },
  writing: { text: "text-skill-writing", bg: "bg-skill-writing/12", dot: "bg-skill-writing" },
  engineering: {
    text: "text-skill-engineering",
    bg: "bg-skill-engineering/12",
    dot: "bg-skill-engineering",
  },
  operations: {
    text: "text-skill-operations",
    bg: "bg-skill-operations/12",
    dot: "bg-skill-operations",
  },
  data: { text: "text-skill-data", bg: "bg-skill-data/12", dot: "bg-skill-data" },
  other: { text: "text-skill-other", bg: "bg-skill-other/12", dot: "bg-skill-other" },
};

export function resolveSkillIcon(meta: SkillPresentationMeta): LucideIcon {
  return SKILL_ICON_COMPONENTS[resolveSkillIconName(meta)];
}
