import type { z } from "zod";
import type * as schemas from "../api/project-p1-schemas";
export type ProjectCapabilities = z.infer<typeof schemas.ProjectCapabilitiesSchema>;
export type ProjectPlanningTimezone = z.infer<typeof schemas.ProjectPlanningTimezoneSchema>;
export type ProjectStatisticsSnapshot = z.infer<typeof schemas.ProjectStatisticsSnapshotSchema>;
export type ProjectOverview = z.infer<typeof schemas.ProjectOverviewSchema>;
export type ProjectRiskSignal = z.infer<typeof schemas.ProjectRiskSignalSchema>;
export type ProjectRiskPage = z.infer<typeof schemas.ProjectRiskPageSchema>;
export type ProjectHistoricalMember = z.infer<typeof schemas.HistoricalMemberSchema>;
export type ProjectEvidenceInput = z.infer<typeof schemas.ProjectEvidenceInputSchema>;
export type ProjectEvidenceView = z.infer<typeof schemas.ProjectEvidenceViewSchema>;
export type ProjectUpdateDraft = z.infer<typeof schemas.ProjectUpdateDraftSchema>;
export type ProjectUpdatePreview = z.infer<typeof schemas.ProjectUpdatePreviewSchema>;
export type ProjectUpdateRevision = z.infer<typeof schemas.ProjectUpdateRevisionSchema>;
export type ProjectUpdate = z.infer<typeof schemas.ProjectUpdateSchema>;
export type ProjectUpdatesPage = z.infer<typeof schemas.ProjectUpdatesPageSchema>;
export type ProjectUpdateRevisionsPage = z.infer<typeof schemas.ProjectUpdateRevisionsPageSchema>;
export type ProjectUpdateWriteInput = z.infer<typeof schemas.ProjectUpdateWriteInputSchema>;
export type ProjectUpdateWriteResult = z.infer<typeof schemas.ProjectUpdateWriteResultSchema>;
export type ProjectDeleteImpact = z.infer<typeof schemas.ProjectDeleteImpactSchema>;
